name: servicerequest
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  google_maps_flutter: ^0.5.28+1
  geolocator: ^5.3.2+2
  provider: ^4.1.3
  http: ^0.12.1
  flutter_rating_bar: ^3.0.1+1
  flutter_text_justify_rtl: ^0.0.4
  intl: ^0.16.1
  get_it: ^4.0.2
  flutter_spinkit: ^4.1.2+1
  shared_preferences: ^0.5.8
  font_awesome_flutter: ^8.8.1
  pin_code_fields: ^4.0.0





dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/marker.png
    - images/wheel.png
    - images/wokshop.png
    - images/car.png
    - images/profile.png
    - images/redmark.png
    - images/providerMarker.png
    - images/noCar.png
    - images/date.png
    - images/carPrimary.png
    - images/location.png
    - images/Login_logo.png
    - images/share_facebook_active.png
    - images/facebook_logo.png
    - images/googlePlus.png
    - images/login_Phone-1.png
    - lang/ar.json
    - lang/en.json


  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/Cairo-Black.ttf
          weight: 900
        - asset: fonts/Cairo-Bold.ttf
          weight: 700
        - asset: fonts/Cairo-ExtraLight.ttf
          weight: 300
        - asset: fonts/Cairo-Light.ttf
          weight: 400
        - asset: fonts/Cairo-Regular.ttf
          weight: 500
        - asset: fonts/Cairo-SemiBold.ttf
          weight: 600

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
